# Used by AppEngine
application: gostart
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /.*
  script: _go_app